### ISSUE TITLE
Python project naming convention

### ISSUE THREAD

**Issue by abhi18av** [datascience-practice-projects/Visualizing-Inequalities-in-Life-Expectancy#1]
- Simple names, why do we need `datascience-practice- ...` in the name?
- Use alphabet casing properly like `visualizing-inequalities-in-life-expectancy`

I've updated the name for this project, please keep this in mind for future.

**Comment by abhi18av** [comment]
CC @Sarvam-Mittal

**Comment by Sarvam-Mittal** [comment]
Okie , Will take care ..
